version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: vue-router
    versions:
    - 4.0.5
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.5.0
    - 7.6.0
    - 7.7.0
  - dependency-name: pug-code-gen
    versions:
    - 2.0.3
  - dependency-name: vuetify
    versions:
    - 2.4.3
    - 2.4.4
    - 2.4.5
  - dependency-name: "@vue/cli-plugin-eslint"
    versions:
    - 4.5.11
  - dependency-name: "@vue/cli-plugin-typescript"
    versions:
    - 4.5.11
  - dependency-name: "@vue/cli-service"
    versions:
    - 4.5.11
  - dependency-name: "@vue/cli-plugin-babel"
    versions:
    - 4.5.11
  - dependency-name: "@mdi/font"
    versions:
    - 5.9.55
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
  - dependency-name: axios
    versions:
    - 0.21.1
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: json-server
    versions:
    - 0.16.3
